### ISSUE TITLE
zfcuser doctrine config

### ISSUE THREAD

**Issue by bgallagher** [goalio/GoalioForgotPasswordDoctrineORM#1]
Hey,

Just getting around to setting this up now.

I see here https://github.com/goalio/GoalioForgotPasswordDoctrineORM/blob/master/Module.php#L19 that your module is attempting to add the ZfcUser doctrine metadata to the driver chain? Is this a hangover from a copy/paste?

Happy to help out and PR.

Brian

**Comment by bgallagher** [comment]
FYI I'm working through the issues here https://github.com/bgallagher/GoalioForgotPasswordDoctrineORM, will PR when it's working.

**Comment by pdobrigkeit** [comment]
Hi Brian,

thanks a lot. Currently I am at a completely different module of our application, so I really appreciate the help on this ;)

Von: Brian Gallagher [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. Februar 2013 17:10
An: goalio/GoalioForgotPasswordDoctrineORM
Betreff: Re: [GoalioForgotPasswordDoctrineORM] zfcuser doctrine config (#1)

FYI I'm working through the issues here https://github.com/bgallagher/GoalioForgotPasswordDoctrineORM, will PR when it's working.

**Comment by bgallagher** [comment]
No problem, it's working locally now for me with Zend\Mail\Transport\File. Will try and confirm it working in production either tomorrow or Monday. Can PR now or then?

One question though, are you incorrectly using the serveUrl view helper here https://github.com/goalio/GoalioForgotPassword/blob/master/view/goalio-forgot-password/email/forgot.phtml#L4 ?

In my reset emails i'm seeing a reset link like "http://wripl.devhttp://wripl.dev/reset-password/1/37C6608E6A5DAFB"

I've never user this helper before, but from looking at the source, it would appear that you're supposed to provide a relative URL instead of an absolute as supplied by the url view helper.
