### ISSUE TITLE
Add tag for v0.*

### ISSUE THREAD

**Issue by Colmea** [goalio/GoalioForgotPasswordDoctrineORM#10]
Hi @pdobrigkeit ,

could you please add a release tag for a 0.\* version ?
I still use zfcUser 0.\* and so goalioForgotPassword 0.\* . But since my last "composer update", I'm not able to go back to a previous version of your module.

My prod server is down, so I hope you will see this issue asap ;)

**Comment by pdobrigkeit** [comment]
Hey, I hope I created a working release 0.9... Please try it out.

**Comment by Colmea** [comment]
Everything works as expected.

Thanks for you fast answer !
