### ISSUE TITLE
Create a repo for the doctrine mongodb odm as well

### ISSUE THREAD

**Issue by dorongutman** [goalio/GoalioForgotPasswordDoctrineORM#3]
I will make the appropriate changes

**Comment by dorongutman** [comment]
Most of the code is ready, just please create a repo for it so I could commit it.

**Comment by pdobrigkeit** [comment]
Hello, I created a repo at https://github.com/goalio/GoalioForgotPasswordDoctrineMongoODM

**Comment by dorongutman** [comment]
Thanks @pdobrigkeit, I saw it and already committed, pushed, and PR'd everything. - https://github.com/goalio/GoalioForgotPasswordDoctrineMongoODM/pull/1

If you could have a look and comment, suggest fixes or merge the PR, that'd be awesome.
Thanks.
